Repository BHoM/BHoM_Adapter, pull requests merged in 2019-10, with the labels that each got.

#136 BHoM_Adapter: Mapping of IDs to dependencyObjects
  BHoM_Adapter/CRUD/Replace.cs
Labels: severity:critical, size:S, status:WIP, type:bug

#144 File_Adapter: If no fileName extension is specified, defaults to .json
  File_Adapter/FileAdapter.cs
Labels: severity:low, size:XS

#154 Updated AssemblyVersion and AssemblyFileVersion to 3.0.0.0
  BHoM_Adapter/Properties/AssemblyInfo.cs
  File_Adapter/Properties/AssemblyInfo.cs
Labels: type:compliance
