Repository BHoM/BHoM_Adapter, pull requests merged in 2020-02, with the labels that each got.

#195 Added description of PushTypes in the enum to be visible in UI's tooltip
  Adapter_oM/enums/PushType.cs
Labels: size:XS, type:feature

#193 Update IElement references with the Dimensional_oM
  Structure_AdapterModule/Structure_AdapterModules.csproj
Labels: type:compliance

#199 Added null check in AssignNextFreeId
  BHoM_Adapter/AdapterActions/_PushMethods/ExternalId/AssignId.cs
Labels: type:feature
